import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import UserLists from "@/components/UserList/UserLists";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-blue-900">{children}</body>
    </html>
  );
}
